### PR TITLE
Added support for timeouts

### PR DESCRIPTION
**Pull request by taraldb**
Sometimes we experience that a job hangs. Implementing timeouts to enable a request to stop itself if it doesn't finish in time.

https://requests.readthedocs.io/en/master/user/quickstart/#timeouts

### CODE REVIEW

**Comment by taraldb** [comment]
Readme.rst is not updated and must be done before merging.

**Review by ploner — APPROVED** [review]
perfect!

**Review by danbahrami — APPROVED** [review]
This is great 💯. Thanks for making this contribution. I'm going to merge and release as version `1.1.0`.

**Comment by danbahrami** [comment]
@narils @ploner `v1.1.0` is now available on pypi

https://pypi.org/project/geckoboard.py

Thanks again 👏

**Pull request merged**
